-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Subjects Table
create table if not exists subjects (
  id text primary key,
  title text not null,
  description text,
  icon_name text, -- We will store the icon name (e.g., 'FlaskConical')
  color text
);

-- Courses Table
create table if not exists courses (
  id text primary key,
  subject_id text references subjects(id) on delete cascade,
  title text not null
);

-- Topics Table
create table if not exists topics (
  id text primary key,
  course_id text references courses(id) on delete cascade,
  title text not null,
  "order" integer generated by default as identity
);

-- Questions Table
create table if not exists questions (
  id bigint primary key, -- Using the existing numeric IDs (e.g., 1001)
  topic_id text references topics(id) on delete cascade,
  text text not null,
  options jsonb not null, -- Stores ["Option A", "Option B"]
  correct_answer integer not null,
  explanation text,
  difficulty text default 'Medium'
);

-- Enable Row Level Security (RLS)
alter table subjects enable row level security;
alter table courses enable row level security;
alter table topics enable row level security;
alter table questions enable row level security;

-- Create Policies (Public Read Access)
create policy "Public subjects are viewable by everyone" on subjects for select using (true);
create policy "Public courses are viewable by everyone" on courses for select using (true);
create policy "Public topics are viewable by everyone" on topics for select using (true);
create policy "Public questions are viewable by everyone" on questions for select using (true);

-- Create Policies (Insert Access - for migration)
-- Ideally, this should be restricted, but for this setup we'll allow authenticated users to insert
-- or you can run the migration script with a service role key if available (not available in client).
-- For now, we allow authenticated users to insert for the migration step.
create policy "Authenticated users can insert subjects" on subjects for insert to authenticated with check (true);
create policy "Authenticated users can insert courses" on courses for insert to authenticated with check (true);
create policy "Authenticated users can insert topics" on topics for insert to authenticated with check (true);
create policy "Authenticated users can insert questions" on questions for insert to authenticated with check (true);
